name: AI SQL Restore

on:
  workflow_dispatch:
    inputs:
      command:
        description: "Enter restore command"
        required: true

jobs:
  run-agent:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.14'

      - name: Install dependencies
        run: |
          pip install pyodbc python-dotenv

      - name: Run AI Agent
        run: |
          python run_agent.py "${{ github.event.inputs.command }}"
